// FOG ITCH API KEY = f3p8kQSK3qc5Ee01jsPjuYILTD3VBq7ya7D9Pg16

const allGames = {  
    "games":[  
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":true,
                "height":600,
                "width":960
            },
            "p_osx":false,
            "id":94510,
            "published":true,
            "published_at":"2016-10-30 20:04:02",
            "views_count":137,
            "url":"https://fog-icmc.itch.io/alex-baphomel-in-the-house-of-satalin",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2016-10-30 20:00:41",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":22,
            "has_demo":false,
            "title":"Alex Baphomel ― in the House of Satalin",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvOTQ1MTAvNDQ2NDg4LnBuZw==/315x250%23c/CVcEIW.png",
            "min_price":0,
            "classification":"game",
            "short_text":"In the devil's house, blink is a terrible idea.",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":304414,
            "published":false,
            "views_count":0,
            "url":"https://fog-icmc.itch.io/allpunk",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2018-09-11 21:55:41",
            "title":"All Punk",
            "has_demo":false,
            "in_press_system":true,
            "min_price":0,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "p_windows":false,
            "downloads_count":0,
            "classification":"game",
            "short_text":"A steampunk game metroidvania like. Play as a cyberpunk robot thats colect steampunk parts.",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":true,
                "height":540,
                "width":960
            },
            "p_osx":false,
            "id":83621,
            "published":true,
            "published_at":"2016-09-05 18:17:50",
            "views_count":513,
            "url":"https://fog-icmc.itch.io/bipolar",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2016-09-03 22:15:17",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":86,
            "has_demo":false,
            "title":"Bipolar",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvODM2MjEvMzk0MDcwLnBuZw==/315x250%23c/2JmZGY.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Many robots, two colors, one challenge: save them all!",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":360,
                "width":640
            },
            "p_osx":false,
            "id":308313,
            "published":true,
            "published_at":"2018-09-23 15:57:11",
            "views_count":46,
            "url":"https://dreammer.itch.io/boss-hammer",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2018-09-23 15:42:55",
            "user":{  
                "url":"https://dreammer.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvNzcxMzkyLzk1MTc0Mi5wbmc=/100x100%23/t7s3TV.png",
                "username":"Dreammer",
                "id":771392
            },
            "downloads_count":4,
            "has_demo":false,
            "title":"Boss Hammer",
            "in_press_system":false,
            "p_windows":false,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMzA4MzEzLzE1MTQxMDIucG5n/315x250%23c/d6pKGe.png",
            "min_price":0,
            "classification":"game",
            "short_text":"a big boss killing mages",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":305301,
            "published":true,
            "published_at":"2018-09-15 00:17:26",
            "views_count":73,
            "url":"https://fog-icmc.itch.io/bukidami-mountain",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2018-09-14 22:30:10",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":21,
            "title":"Bukidami Mountain",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMzA1MzAxLzE1MjUzNDQucG5n/315x250%23c/R7%2BJq%2B.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Puzzle-platformer game about a village man exploring a mysterious mountain.",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":307330,
            "published":false,
            "views_count":0,
            "url":"https://fog-icmc.itch.io/capyslock",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "p_windows":false,
            "has_demo":false,
            "created_at":"2018-09-20 17:01:47",
            "in_press_system":true,
            "title":"Capyslock",
            "min_price":0,
            "downloads_count":0,
            "classification":"game",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":305304,
            "published":true,
            "published_at":"2018-09-19 12:22:01",
            "views_count":63,
            "url":"https://fog-icmc.itch.io/dragoes",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2018-09-14 22:35:14",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":9,
            "title":"Caverna dos Dragões",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMzA1MzA0LzE1MDY1ODUucG5n/315x250%23c/NsyKSx.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Explore the cave and hit dragons with a wrench!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":600,
                "width":960
            },
            "p_osx":true,
            "id":85863,
            "published":true,
            "published_at":"2016-10-11 18:53:58",
            "views_count":1113,
            "url":"https://fog-icmc.itch.io/chronochromatic",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2016-09-16 16:20:09",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":127,
            "has_demo":false,
            "title":"ChronoChromatic",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvODU4NjMvNDA0ODU2LnBuZw==/315x250%23c/w2wI8g.png",
            "min_price":0,
            "classification":"game",
            "short_text":"A colorful and rhythmic puzzle that will certainly challenge you!",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":650,
                "width":1000
            },
            "p_osx":false,
            "id":82064,
            "published":true,
            "published_at":"2016-08-29 00:17:16",
            "views_count":1024,
            "url":"https://fog-icmc.itch.io/churros-empire",
            "can_be_bought":false,
            "p_android":true,
            "p_linux":true,
            "created_at":"2016-08-28 19:11:20",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":85,
            "has_demo":false,
            "title":"Churros Empire",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvODIwNjQvMzg2NzI4LnBuZw==/315x250%23c/D%2Fllv1.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Conquer the whole universe with your Churros!",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":true,
                "height":360,
                "width":640
            },
            "p_osx":false,
            "id":305303,
            "published":false,
            "views_count":1,
            "url":"https://fog-icmc.itch.io/corrida-eleitoral",
            "can_be_bought":false,
            "p_android":true,
            "p_linux":false,
            "created_at":"2018-09-14 22:33:23",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":5,
            "title":"Corrida Eleitoral 2018",
            "p_windows":false,
            "cover_url":"https://img.itch.zone/aW1nLzE2MDc5NzcucG5n/315x250%23c/Hx%2FF5B.png",
            "min_price":0,
            "classification":"game",
            "short_text":"The electoral race to the Brazilian presidency 2018",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":161947,
            "published":true,
            "published_at":"2017-08-31 23:13:17",
            "views_count":31,
            "url":"https://fog-icmc.itch.io/crystalrise",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2017-07-26 20:24:38",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":7,
            "title":"Crystal Rise",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTYxOTQ3LzgwMTU0NC5wbmc=/315x250%23c/BditPi.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Quickly climb the crystal blocks, and knock down your enemies!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":121493,
            "published":true,
            "published_at":"2017-02-21 03:34:21",
            "views_count":101,
            "url":"https://fog-icmc.itch.io/cute-but-dangerous",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2017-02-21 02:46:03",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":23,
            "title":"Cute but Dangerous",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTIxNDkzLzU1OTY4Ni5wbmc=/315x250%23c/k4SvXu.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Avoid everything, even the cutest.",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":305539,
            "published":true,
            "published_at":"2018-09-20 17:45:28",
            "views_count":41,
            "url":"https://fog-icmc.itch.io/cyberbunny",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2018-09-15 16:01:54",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":16,
            "title":"Cyberbunny",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMzA1NTM5LzE1MjUyOTgucG5n/315x250%23c/zJBU3T.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Escape from the office and save the world with Cyberbunny!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":165864,
            "published":true,
            "published_at":"2017-08-05 15:23:20",
            "views_count":5,
            "url":"https://fog-icmc.itch.io/days-at-the-park",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2017-08-05 13:16:36",
            "in_press_system":true,
            "has_demo":false,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "title":"Days at the Park",
            "downloads_count":1,
            "p_windows":true,
            "min_price":0,
            "classification":"game",
            "short_text":"Dê um passeio no parque e abraçe bichos fofinhos. Ou sera que há algo sombrio por trás...",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":324239,
            "published":false,
            "views_count":0,
            "url":"https://fog-icmc.itch.io/dnjs22",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2018-10-31 17:34:21",
            "title":"DNJS22",
            "in_press_system":true,
            "has_demo":false,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "min_price":0,
            "p_windows":false,
            "cover_url":"https://img.itch.zone/aW1nLzE2MDI1MDAucG5n/315x250%23c/bUFRXH.png",
            "downloads_count":0,
            "classification":"game",
            "short_text":"Batalhe entre equipes para garantir a dominação  total do recurso natual mais valioso: café!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":312471,
            "published":true,
            "published_at":"2018-10-05 17:32:32",
            "views_count":20,
            "url":"https://fog-icmc.itch.io/ecoedu",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2018-10-03 14:46:14",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":1,
            "title":"EcoEdu",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1nLzE1MzYwMDQucG5n/315x250%23c/iYqZAJ.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Learn about recycling and keep the city clean!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":615,
                "width":975
            },
            "p_osx":false,
            "id":176030,
            "published":true,
            "published_at":"2017-09-23 18:23:32",
            "views_count":336,
            "url":"https://fog-icmc.itch.io/eodun",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2017-09-16 19:02:53",
            "in_press_system":true,
            "downloads_count":13,
            "min_price":0,
            "has_demo":false,
            "p_windows":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTc2MDMwLzgzMDYyNy5naWY=/315x250%23c/BJ68VM.gif",
            "still_cover_url":"https://img.itch.zone/aW1hZ2UvMTc2MDMwLzgzMDYyNy5naWY=/315x250%23cm/9JYb8m.gif",
            "title":"Eodun",
            "classification":"game",
            "short_text":"Fight against endless hordes with your spriritual partner",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":176031,
            "published":true,
            "published_at":"2018-05-23 14:22:06",
            "views_count":38,
            "url":"https://fog-icmc.itch.io/eratd",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2017-09-16 19:03:21",
            "title":"ERA TD",
            "has_demo":false,
            "p_windows":true,
            "in_press_system":true,
            "downloads_count":5,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTc2MDMxLzgzNjY2MS5wbmc=/315x250%23c/UtfjvY.png",
            "min_price":0,
            "classification":"game",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "type":"default"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":600,
                "width":960
            },
            "p_osx":false,
            "id":91507,
            "published":true,
            "published_at":"2016-12-07 16:42:35",
            "views_count":221,
            "url":"https://fog-icmc.itch.io/ermo",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2016-10-15 13:54:22",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":22,
            "has_demo":false,
            "title":"Ermo",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvOTE1MDcvNDc0NDk3LnBuZw==/315x250%23c/qgLoQW.png",
            "min_price":0,
            "classification":"game",
            "short_text":"A scary forest filled with monsters. The catch? You are defenseless and alone...",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":480,
                "width":640
            },
            "p_osx":false,
            "id":176033,
            "published":true,
            "published_at":"2017-09-21 07:00:17",
            "views_count":269,
            "url":"https://fog-icmc.itch.io/escape-jon",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2017-09-16 19:04:02",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":38,
            "has_demo":false,
            "title":"Escape Jon",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTc2MDMzLzgyMzMyNy5wbmc=/315x250%23c/6BVco5.png",
            "min_price":0,
            "classification":"game",
            "short_text":"In a house full of challenges, the goal is simple: ESCAPE!",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":297602,
            "published":true,
            "views_count":10,
            "url":"https://fog-icmc.itch.io/factions-of-glory",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2018-08-26 21:56:10",
            "title":"Factions of Glory",
            "in_press_system":true,
            "has_demo":false,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "min_price":0,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMjk3NjAyLzE0NzM4NTUucG5n/315x250%23c/mYzKgo.png",
            "downloads_count":2,
            "classification":"game",
            "short_text":"Today is a day of Glory!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":297609,
            "published":false,
            "views_count":0,
            "url":"https://fog-icmc.itch.io/farawall",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "p_windows":false,
            "has_demo":false,
            "created_at":"2018-08-26 22:09:06",
            "in_press_system":true,
            "title":"Farawall",
            "min_price":0,
            "downloads_count":0,
            "classification":"game",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":305538,
            "published":true,
            "published_at":"2018-09-15 17:18:50",
            "views_count":84,
            "url":"https://fog-icmc.itch.io/fpb",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2018-09-15 16:00:32",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":21,
            "title":"FPB",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1nLzE1MzUwMDUucG5n/315x250%23c/7gLauX.png",
            "min_price":0,
            "classification":"game",
            "short_text":"First Person Baby",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":600,
                "width":980
            },
            "p_osx":false,
            "id":176029,
            "published":true,
            "published_at":"2017-09-17 02:04:02",
            "views_count":391,
            "url":"https://fog-icmc.itch.io/gatastrofe",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2017-09-16 19:02:18",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":46,
            "has_demo":false,
            "title":"Gatástrofe",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTc2MDI5LzgyMzI2Ni5wbmc=/315x250%23c/xHKBQt.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Did you think cats would dominate the world? About that...",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":true,
                "height":600,
                "width":960
            },
            "p_osx":false,
            "id":94494,
            "published":true,
            "published_at":"2016-10-30 20:31:27",
            "views_count":239,
            "url":"https://fog-icmc.itch.io/gmtm",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2016-10-30 18:28:42",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":12,
            "has_demo":false,
            "title":"GMTM",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvOTQ0OTQvNDQyNzA0LnBuZw==/315x250%23c/8kqCOa.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Listen and see your path. Run for your life. Forever.",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":249006,
            "published":true,
            "published_at":"2018-04-24 00:25:09",
            "views_count":94,
            "url":"https://bibicio.itch.io/guerrinha",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2018-04-23 17:33:13",
            "in_press_system":false,
            "user":{  
                "display_name":"Fabrício Guedes Faria",
                "id":286721,
                "url":"https://bibicio.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjg2NzIxLzEwODk3NTIuanBn/100x100%23/c6WFTC.jpg",
                "username":"bibicio"
            },
            "has_demo":false,
            "downloads_count":30,
            "title":"Guerrinha",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMjQ5MDA2LzExOTIwOTEucG5n/315x250%23c/jGxj5e.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Um jogo de tiro com arminhas de dedo!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":360,
                "width":640
            },
            "p_osx":true,
            "id":250389,
            "published":true,
            "published_at":"2018-05-26 11:13:04",
            "views_count":531,
            "url":"https://fog-icmc.itch.io/hexcasters",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2018-04-24 23:27:05",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":44,
            "has_demo":false,
            "title":"HexCasters",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMjUwMzg5LzE0Nzg0MTEucG5n/315x250%23c/ZeQPvy.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Turn-based strategy game with combinations of magic spells",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":297288,
            "published":false,
            "views_count":0,
            "url":"https://fog-icmc.itch.io/internet-guido",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "p_windows":false,
            "has_demo":false,
            "created_at":"2018-08-25 21:17:33",
            "in_press_system":true,
            "title":"Internet Guido",
            "min_price":0,
            "downloads_count":0,
            "classification":"game",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":165871,
            "published":true,
            "published_at":"2017-08-05 22:29:06",
            "views_count":78,
            "url":"https://fog-icmc.itch.io/jogo-do-bixo",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2017-08-05 13:42:05",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":1,
            "title":"Jogo do Bixo",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTY1ODcxLzc2NjczOC5wbmc=/315x250%23c/LJgQoQ.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Prove que você é um dos dignos!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":600,
                "width":1024
            },
            "p_osx":true,
            "id":143807,
            "published":true,
            "published_at":"2017-05-14 22:41:34",
            "views_count":176,
            "url":"https://fog-icmc.itch.io/knights-and-damsels",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2017-05-14 21:33:54",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":11,
            "has_demo":false,
            "title":"Knights and Damsels",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTQzODA3LzY1OTAwNy5wbmc=/315x250%23c/KhgiTy.png",
            "min_price":0,
            "classification":"game",
            "short_text":"You have to win, but remember: your knights are people.",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":305308,
            "published":false,
            "views_count":0,
            "url":"https://fog-icmc.itch.io/labirinto-da-fisica",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "p_windows":true,
            "in_press_system":true,
            "has_demo":false,
            "downloads_count":6,
            "min_price":0,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "created_at":"2018-09-14 22:46:49",
            "cover_url":"https://img.itch.zone/aW1hZ2UvMzA1MzA4LzE1MDY3NDcucG5n/315x250%23c/Wgdbr4.png",
            "classification":"game",
            "title":"Labirinto da Física",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":360,
                "width":640
            },
            "p_osx":false,
            "id":161945,
            "published":true,
            "published_at":"2018-02-28 01:25:45",
            "views_count":91,
            "url":"https://fog-icmc.itch.io/magnum-opus",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2017-07-26 20:23:03",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":2,
            "has_demo":false,
            "title":"Magnum Opus",
            "in_press_system":true,
            "p_windows":false,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTYxOTQ1LzgyNzIyMi5wbmc=/315x250%23c/sl8Dd2.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Become an alchemist and come closer to the truth!",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":true,
                "height":600,
                "width":1000
            },
            "p_osx":false,
            "id":237294,
            "published":true,
            "published_at":"2018-03-26 20:44:13",
            "views_count":262,
            "url":"https://dalacqua.itch.io/mar-do-saber",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2018-03-22 02:35:35",
            "user":{  
                "url":"https://dalacqua.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvODg5NDQwLzExMzA0NTMuanBn/100x100%23/hvFvFk.jpg",
                "username":"dalacqua",
                "id":889440
            },
            "downloads_count":15,
            "has_demo":false,
            "title":"Mar Do Saber",
            "in_press_system":false,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMjM3Mjk0LzExNDY2NzgucG5n/315x250%23c/uJPUQj.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Transforme-se em um mergulhador e fotógrafo a procura de fotos de criaturas marinhas.",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":540,
                "width":977
            },
            "p_osx":true,
            "id":176032,
            "published":true,
            "published_at":"2017-09-23 18:28:37",
            "views_count":131,
            "url":"https://fog-icmc.itch.io/meta",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2017-09-16 19:03:41",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":2,
            "has_demo":false,
            "title":"MeTa",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTc2MDMyLzgzMTA1OS5wbmc=/315x250%23c/j8cVwP.png",
            "min_price":0,
            "classification":"game",
            "short_text":"A medieval game... Until you realize that no!",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":250066,
            "published":true,
            "published_at":"2018-04-24 04:54:11",
            "views_count":217,
            "url":"https://arsart.itch.io/midiwave",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2018-04-24 04:30:57",
            "in_press_system":false,
            "user":{  
                "display_name":"Arthur Souza",
                "id":229243,
                "url":"https://arsart.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI5MjQzLzExOTM5NjYuanBn/100x100%23/6O2k3a.jpg",
                "username":"Arsart"
            },
            "has_demo":false,
            "downloads_count":61,
            "title":"Midi&wave",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMjUwMDY2LzExOTM4OTQucG5n/315x250%23c/%2BOcfYj.png",
            "min_price":0,
            "classification":"game",
            "short_text":"A mix of a Metroidvania and Escape the Room genres, using the Vaporwave and Medieval themes.",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":600,
                "width":960
            },
            "p_osx":false,
            "id":113638,
            "published":true,
            "published_at":"2017-01-22 21:16:55",
            "views_count":148,
            "url":"https://fog-icmc.itch.io/momma-crab",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2017-01-22 21:16:06",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":21,
            "has_demo":false,
            "title":"Momma Crab",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTEzNjM4LzUyNzYxOC5wbmc=/315x250%23c/XLyu7W.png",
            "min_price":0,
            "classification":"game",
            "short_text":"An audacious crab fights wrath of the waves to bring home food for her children",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":true,
                "height":360,
                "width":640
            },
            "p_osx":false,
            "id":298938,
            "published":true,
            "published_at":"2018-08-30 23:27:27",
            "views_count":69,
            "url":"https://fog-icmc.itch.io/multi-task",
            "can_be_bought":false,
            "p_android":true,
            "p_linux":true,
            "created_at":"2018-08-30 23:19:41",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":5,
            "has_demo":false,
            "title":"MulTI Task",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMjk4OTM4LzE0Njc0MzcucG5n/315x250%23c/UU6qhC.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Um jogo de microgames sobre ser um Suporte de Informática",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":360,
                "width":640
            },
            "p_osx":false,
            "id":306648,
            "published":true,
            "published_at":"2018-09-18 20:16:20",
            "views_count":58,
            "url":"https://fog-icmc.itch.io/natty-marie",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2018-09-18 17:27:01",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":0,
            "has_demo":false,
            "title":"Natty Marie",
            "in_press_system":true,
            "p_windows":false,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMzA2NjQ4LzE1MjE5NDYucG5n/315x250%23c/rV5ftx.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Escape from the nightmare with Natty Marie!",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":235820,
            "published":true,
            "published_at":"2018-04-02 15:28:52",
            "views_count":136,
            "url":"https://fog-icmc.itch.io/ottershootout",
            "can_be_bought":false,
            "p_android":true,
            "p_linux":false,
            "created_at":"2018-03-17 22:40:55",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":19,
            "title":"Otter Shootout",
            "p_windows":false,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMjM1ODIwLzEzNDI1MDkucG5n/315x250%23c/WfWYbM.png",
            "min_price":0,
            "classification":"game",
            "short_text":"A duel of otter versus otter!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":165865,
            "published":true,
            "published_at":"2017-08-05 17:53:05",
            "views_count":71,
            "url":"https://fog-icmc.itch.io/pega",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2017-08-05 13:20:38",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":9,
            "title":"Pega",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTY1ODY1Lzc2NjQwNi5wbmc=/315x250%23c/8ivra6.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Get the data to escape the labyrinth!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":305513,
            "published":true,
            "published_at":"2018-09-15 15:33:25",
            "views_count":67,
            "url":"https://fog-icmc.itch.io/persecution",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2018-09-15 14:52:22",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":11,
            "has_demo":false,
            "p_windows":true,
            "min_price":0,
            "cover_url":"https://img.itch.zone/aW1nLzE1NzAyNjUuZ2lm/315x250%23c/8IS2cQ.gif",
            "still_cover_url":"https://img.itch.zone/aW1nLzE1NzAyNjUuZ2lm/315x250%23cm/jF3bIW.gif",
            "title":"Persecution",
            "classification":"game",
            "short_text":"Paranoid Schizophrenia breakout simulation",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":650,
                "width":1000
            },
            "p_osx":false,
            "id":82483,
            "published":true,
            "published_at":"2016-08-30 00:26:38",
            "views_count":1296,
            "url":"https://fog-icmc.itch.io/picross",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2016-08-29 20:05:22",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":165,
            "has_demo":false,
            "title":"PiCross",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvODI0ODMvMzg4NjcwLnBuZw==/315x250%23c/npguXM.png",
            "min_price":0,
            "classification":"game",
            "short_text":"A classic puzzle game in a modern (and colorful) design",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":600,
                "width":1024
            },
            "p_osx":true,
            "id":186292,
            "published":true,
            "published_at":"2017-10-23 01:32:49",
            "views_count":201,
            "url":"https://fog-icmc.itch.io/por-um-fio",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2017-10-22 19:29:36",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":12,
            "has_demo":false,
            "title":"Por um Fio",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTg2MjkyLzg3MTc1NS5wbmc=/315x250%23c/%2FO8mlF.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Try to solve puzzles while being stuck to your friend",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":true,
                "height":600,
                "width":960
            },
            "p_osx":false,
            "id":128406,
            "published":true,
            "published_at":"2017-08-05 17:40:17",
            "views_count":423,
            "url":"https://fog-icmc.itch.io/pao-na-chapa-simulator",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2017-03-19 17:52:20",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":24,
            "has_demo":false,
            "title":"Pão na Chapa Simulator",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTI4NDA2Lzc2NjQwMC5wbmc=/315x250%23c/%2F5f%2Ft1.png",
            "min_price":0,
            "classification":"game",
            "short_text":"The students want food and you want to earn money!",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "p_osx":true,
            "id":316008,
            "published":true,
            "published_at":"2018-10-20 21:24:55",
            "views_count":32,
            "url":"https://fog-icmc.itch.io/regnum",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2018-10-12 14:34:46",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":3,
            "title":"Regnum",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1nLzE1NTY1NDYucG5n/315x250%23c/xopH1f.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Challenge yourself with a new type of chess!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":308280,
            "published":true,
            "published_at":"2018-09-23 16:11:21",
            "views_count":69,
            "url":"https://abnersantos.itch.io/shoot-em-down",
            "can_be_bought":false,
            "p_android":true,
            "p_linux":false,
            "created_at":"2018-09-23 13:49:47",
            "in_press_system":false,
            "user":{  
                "url":"https://abnersantos.itch.io",
                "username":"AbnerSantos",
                "id":1214775
            },
            "has_demo":false,
            "downloads_count":30,
            "title":"Shoot 'Em Down",
            "p_windows":false,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMzA4MjgwLzE1MTQxNzkucG5n/315x250%23c/86fWgh.png",
            "min_price":0,
            "classification":"game",
            "short_text":"A Shoot 'Em Up where you're the boss!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":165878,
            "published":true,
            "published_at":"2017-08-05 18:41:34",
            "views_count":232,
            "url":"https://fog-icmc.itch.io/spacemonium",
            "can_be_bought":false,
            "p_android":true,
            "p_linux":false,
            "created_at":"2017-08-05 14:13:09",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":35,
            "title":"Spacemonium",
            "p_windows":false,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTY1ODc4Lzc2NjU1OC5wbmc=/315x250%23c/RRRSF1.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Travel through space and fight countless enemies!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":true,
                "height":600,
                "width":1067
            },
            "p_osx":true,
            "id":157936,
            "published":true,
            "published_at":"2017-08-07 14:35:50",
            "views_count":743,
            "url":"https://fog-icmc.itch.io/stack",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2017-07-12 18:50:03",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":81,
            "has_demo":false,
            "title":"Stack",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTU3OTM2Lzc3Mzg4Ny5wbmc=/315x250%23c/XeY3Au.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Stacking pieces is not a child game, it's a true challenge!",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":600,
                "width":800
            },
            "p_osx":true,
            "id":83889,
            "published":true,
            "published_at":"2016-09-06 04:42:13",
            "views_count":2212,
            "url":"https://fog-icmc.itch.io/stahlkampf",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2016-09-04 21:57:01",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":239,
            "has_demo":false,
            "title":"Stahlkampf",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvODM4ODkvMzk2NDUzLnBuZw==/315x250%23c/WaYg4I.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Turn-based strategy game set in a dieselpunk Germany",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":305602,
            "published":true,
            "published_at":"2018-10-02 03:06:24",
            "views_count":31,
            "url":"https://fog-icmc.itch.io/strategic-warfare",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2018-09-15 18:58:39",
            "title":"Strategic Warfare",
            "has_demo":false,
            "p_windows":true,
            "in_press_system":true,
            "downloads_count":2,
            "cover_url":"https://img.itch.zone/aW1nLzE1MzUxMDMucG5n/315x250%23c/%2FANAbv.png",
            "min_price":0,
            "classification":"game",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":167624,
            "published":true,
            "published_at":"2017-08-13 18:12:03",
            "views_count":147,
            "url":"https://fog-icmc.itch.io/tentacao",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2017-08-13 17:59:31",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":25,
            "title":"Tentação: Festa Furtacor",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTY3NjI0Lzc3NjM4MS5wbmc=/315x250%23c/%2FfpGM7.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Play a Brazilian 90s TV game show with your friends!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":307484,
            "published":true,
            "published_at":"2018-09-23 23:40:03",
            "views_count":22,
            "url":"https://fog-icmc.itch.io/thebugwars",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2018-09-21 03:28:55",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":1,
            "title":"The Bug Wars",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1nLzE1MzQ4MzYucG5n/315x250%23c/i43GMf.png",
            "min_price":0,
            "classification":"game",
            "short_text":"A multiplayer fighting game about gang fights in a dystopic future.",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":600,
                "width":800
            },
            "p_osx":false,
            "id":158915,
            "published":true,
            "published_at":"2017-07-16 21:29:17",
            "views_count":422,
            "url":"https://anayagf.itch.io/traveling-light",
            "can_be_bought":false,
            "p_android":true,
            "p_linux":false,
            "created_at":"2017-07-16 08:27:47",
            "user":{  
                "display_name":"Anayã Gimenes Ferreira",
                "id":267149,
                "url":"https://anayagf.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjY3MTQ5LzQ0Mjc1Mi5wbmc=/100x100%23/uNN0uk.png",
                "username":"anayagf"
            },
            "downloads_count":46,
            "has_demo":false,
            "title":"Traveling Light",
            "in_press_system":false,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTU4OTE1Lzc3Nzc0Ni5wbmc=/315x250%23c/5LLnPa.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Roll along... Don't get zapped! Don't fall down!",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":53264,
            "published":false,
            "views_count":0,
            "url":"https://gabtoschi.itch.io/tribalis",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "p_windows":false,
            "in_press_system":true,
            "has_demo":false,
            "downloads_count":0,
            "min_price":0,
            "user":{  
                "display_name":"Gabriel Toschi",
                "id":29496,
                "url":"https://gabtoschi.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjk0OTYvNDI2ODcwLnBuZw==/100x100%23/N3on8k.png",
                "username":"gabtoschi"
            },
            "created_at":"2016-02-03 20:03:12",
            "cover_url":"https://img.itch.zone/aW1hZ2UvNTMyNjQvMjM2NjA1LnBuZw==/315x250%23c/FJ7QK3.png",
            "classification":"game",
            "title":"Tribalis",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":176034,
            "published":true,
            "published_at":"2017-09-19 16:41:19",
            "views_count":133,
            "url":"https://fog-icmc.itch.io/triangulo-ao-quadrado",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2017-09-16 19:04:38",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":7,
            "title":"Triângulo ao Quadrado",
            "p_windows":false,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTc2MDM0LzgyMjI5Ni5wbmc=/315x250%23c/vRhCk9.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Escape from the triangle factory with your lucky hammer!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":121524,
            "published":true,
            "published_at":"2017-02-21 05:39:54",
            "views_count":56,
            "url":"https://fog-icmc.itch.io/type-time",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2017-02-21 05:00:05",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":8,
            "title":"Type Time",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTIxNTI0LzU1OTc2NS5wbmc=/315x250%23c/7EUn1n.png",
            "min_price":0,
            "classification":"game",
            "short_text":"A challenge of speed and typing skills.",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":323346,
            "published":true,
            "published_at":"2018-10-30 17:34:43",
            "views_count":99,
            "url":"https://fog-icmc.itch.io/uncivilized",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2018-10-29 19:11:19",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":24,
            "title":"Uncivilized",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1nLzE1OTY5NTQucG5n/315x250%23c/H0gZ4X.png",
            "min_price":0,
            "classification":"game",
            "short_text":"HEXplore, HEXploit, HEXterminate!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":161951,
            "published":false,
            "views_count":12,
            "url":"https://fog-icmc.itch.io/virtuosi",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2017-07-26 20:36:57",
            "title":"Virtuosi!",
            "in_press_system":true,
            "has_demo":false,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "min_price":0,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTYxOTUxLzc2NjQzMy5wbmc=/315x250%23c/RS0M9v.png",
            "downloads_count":9,
            "classification":"game",
            "short_text":"Become a virtuoso and play classical music on your violin!",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "p_osx":false,
            "id":297292,
            "published":true,
            "published_at":"2018-09-10 18:50:04",
            "views_count":564,
            "url":"https://fog-icmc.itch.io/von-rage",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2018-08-25 21:27:41",
            "in_press_system":true,
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "has_demo":false,
            "downloads_count":102,
            "title":"Von Rage",
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMjk3MjkyLzE1MTQ3NjgucG5n/315x250%23c/2n2GCn.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Escape from the park! If you can...",
            "type":"default"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":true,
                "height":600,
                "width":1024
            },
            "p_osx":false,
            "id":138016,
            "published":true,
            "published_at":"2017-04-24 23:27:42",
            "views_count":112,
            "url":"https://fog-icmc.itch.io/watch-your-step",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2017-04-24 20:19:59",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":30,
            "has_demo":false,
            "title":"Watch Your Step",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTM4MDE2LzY1ODkxOC5wbmc=/315x250%23c/56fwnB.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Be careful in this messy house as you travel through the rooms",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":false,
                "height":480,
                "width":640
            },
            "p_osx":false,
            "id":165958,
            "published":true,
            "published_at":"2017-08-05 21:36:47",
            "views_count":32,
            "url":"https://fog-icmc.itch.io/www",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":false,
            "created_at":"2017-08-05 20:48:43",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":2,
            "has_demo":false,
            "title":"Wonderful Wave of Waves",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTY1OTU4Lzc2NjYzMy5wbmc=/315x250%23c/hItwwA.png",
            "min_price":0,
            "classification":"game",
            "short_text":"Defend yourself of the waves!",
            "type":"html"
        },
        {  
            "purchases_count":0,
            "embed":{  
                "fullscreen":true,
                "height":480,
                "width":640
            },
            "p_osx":false,
            "id":140120,
            "published":true,
            "published_at":"2017-04-30 19:34:52",
            "views_count":138,
            "url":"https://fog-icmc.itch.io/world-mower",
            "can_be_bought":false,
            "p_android":false,
            "p_linux":true,
            "created_at":"2017-04-30 19:16:23",
            "user":{  
                "display_name":"Fellowship of the Game",
                "id":227700,
                "url":"https://fog-icmc.itch.io",
                "cover_url":"https://img.itch.zone/aW1hZ2UyL3VzZXIvMjI3NzAwLzEyNTExMzIucG5n/100x100%23/NTxTJ9.png",
                "username":"fog-icmc"
            },
            "downloads_count":8,
            "has_demo":false,
            "title":"World Mower",
            "in_press_system":true,
            "p_windows":true,
            "cover_url":"https://img.itch.zone/aW1hZ2UvMTQwMTIwLzY0MTg5Ni5wbmc=/315x250%23c/UAeXOS.png",
            "min_price":0,
            "classification":"game",
            "short_text":"2D Shmup with SNES mode 7-like background",
            "type":"html"
        }
    ]
}

export default allGames
